"""
Central configuration.

Values come from environment variables (loaded from `.env` in local dev via
python-dotenv, and injected directly by the host in production). Board/column
identifiers come from `board_config.json`, which is generated by the ingestion
script so the app never hardcodes Monday internals.
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

# Load .env from the backend directory if present (no-op in production).
_BACKEND_DIR = Path(__file__).resolve().parent.parent
load_dotenv(_BACKEND_DIR / ".env")

APP_DIR = Path(__file__).resolve().parent
FRONTEND_DIR = _BACKEND_DIR.parent / "frontend"
BOARD_CONFIG_PATH = APP_DIR / "board_config.json"


class Settings:
    """Runtime settings, resolved once at import."""

    def __init__(self) -> None:
        self.monday_api_token: str = os.getenv("MONDAY_API_TOKEN", "").strip()
        self.monday_api_url: str = os.getenv(
            "MONDAY_API_URL", "https://api.monday.com/v2"
        ).strip()

        self.anthropic_api_key: str = os.getenv("ANTHROPIC_API_KEY", "").strip()
        self.anthropic_model: str = os.getenv(
            "ANTHROPIC_MODEL", "claude-haiku-4-5-20251001"
        ).strip()

        self.cache_ttl_seconds: int = int(os.getenv("CACHE_TTL_SECONDS", "300"))
        self.port: int = int(os.getenv("PORT", "8000"))

        # Optional manual overrides for board ids (normally read from board_config.json).
        self._deals_board_override = os.getenv("DEALS_BOARD_ID", "").strip()
        self._wo_board_override = os.getenv("WORK_ORDERS_BOARD_ID", "").strip()

    @property
    def llm_enabled(self) -> bool:
        """True when an Anthropic key is configured; otherwise deterministic-only."""
        return bool(self.anthropic_api_key)

    @property
    def monday_configured(self) -> bool:
        return bool(self.monday_api_token)


settings = Settings()


@lru_cache(maxsize=1)
def load_board_config() -> dict[str, Any]:
    """
    Load the board/column mapping produced by scripts/ingest_to_monday.py.

    Returns an empty structure if the file does not exist yet, so the app can
    still boot (and report that ingestion has not been run) rather than crashing.
    """
    if not BOARD_CONFIG_PATH.exists():
        return {"deals": None, "work_orders": None, "generated_at": None}
    with open(BOARD_CONFIG_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


def board_config_present() -> bool:
    cfg = load_board_config()
    return bool(cfg.get("deals") and cfg.get("work_orders"))
